# Generated by Django 2.2.11 on 2020-03-22 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='picDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataName', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('dataNum', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='picData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, default=0.0, max_digits=8)),
                ('typeData', models.TextField()),
                ('wordData', models.TextField()),
                ('setSource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dataDeal.picDataSet')),
            ],
        ),
    ]
